const carBrands: string[] = [
  'Toyota',
  'Ford',
  'Chevrolet',
  'Honda',
  'Nissan',
  'Volkswagen',
  'Mercedes-Benz',
  'BMW',
  'Audi',
  'Hyundai',
  'Kia',
  'Subaru',
  'Lexus',
  'Mazda',
  'Tesla',
  'Volvo',
  'Buick',
  'Cadillac',
  'GMC',
  'Jeep',
  'Chrysler',
  'Dodge',
  'Acura',
  'Infiniti',
  'Ram',
  'Land Rover',
  'Fiat',
  'Mitsubishi',
  'Porsche',
  'Jaguar',
  'Mini',
  'Aston Martin',
  'Alfa Romeo',
  'Lincoln',
  'Bentley',
  'Ferrari',
  'Maserati',
  'McLaren',
  'Lamborghini',
  'Bugatti',
  'Genesis',
  'Smart',
  'Rolls-Royce',
  'Maybach',
  'Lotus',
  'Koenigsegg',
  'Pagani',
  'Spyker',
  'Faraday Future',
  'Rivian',
  'Lucid Motors',
  'Rimac',
  'Byton',
  'NIO',
  'Polestar',
  'Bollinger',
  'Fisker',
  'Karma',
  'Elio Motors',
  'Hennessey',
  'Aurus',
  'Zenvo',
  'W Motors',
  'Pininfarina',
  'Vanderhall',
  'Rimac',
  'Lykan',
  'Rezvani',
  'De Tomaso',
  'Venturi',
  'Scuderia Cameron Glickenhaus',
  'Triton Solar',
  'Aptera Motors',
  'Nikola Corporation',
  'Epic EV',
  'Alpha Motor Corporation',
  'Canoo',
  'Ineos Grenadier',
  'Rivian',
  'Bollinger Motors',
  'Kandi Technologies',
  'Lordstown Motors',
  'FARADAY FUTURE',
  'Lucid Motors',
  'Canoo',
  'Fisker',
  'Karma Automotive',
  'BYTON',
  'LORDSTOWN MOTORS',
  'Sono Motors',
]

export { carBrands }
